version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=greenfield_qa
      - POSTGRES_PASSWORD=TkY1S361HFaF
    volumes:
      - ./server/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ../efs:/docker-entrypoint-initdb.d/csv
      # - ./server/data:/docker-entrypoint-initdb.d/csv
  server:
    build:
      dockerfile: Dockerfile
      context: './server'
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - postgres
    expose:
      - '5000'
    environment:
      - PGUSER=root
      - PGHOST=postgres
      - PGDATABASE=greenfield_qa
      - PGPASSWORD=TkY1S361HFaF
      - PGPORT=5432
  nginx:
    image: 'nginx:latest'
    privileged: true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - '4000:4000'
volumes:
  database_data:
    driver: local
